/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "EtaPdf.h" 
#include "include/RooAbsReal.h" 
#include "include/RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(EtaPdf) 

 EtaPdf::EtaPdf(const char *name, const char *title, 
                        RooAbsReal& _theta) :
   RooAbsPdf(name,title), 
   theta("theta","theta",this,_theta)
 { 
 } 


 EtaPdf::EtaPdf(const EtaPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   theta("theta",this,other.theta)
 { 
 } 



 Double_t EtaPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return 1/(2*3.1415926535*sin(theta)) ; 
 } 



